import express from "express";
import * as videoController from "../controllers/videoController.js";
import { queue } from "../middleware/limiterHandler.js";
const router = express.Router();
router.post("/upload", queue, videoController.videoUpload);
router.get("/download", videoController.videoDownload);
router.post("/store", videoController.videoStore);
router.delete("/delete", videoController.videoDelete);
router.get("/convert", videoController.videoConvert);
router.get("/videoTest", videoController.test);
router.post("/add", videoController.addShow);
router.get("/get", videoController.getShow);
export default router;
